package petShop.api.domain.veterinario;

public enum Especialidade {

    ANESTESIOLOGIA,
    CARDIOLOGIA,
    CIRURGIA,
    CLINICA_CIRURGIA_PEQUENOS_ANIMAIS,
    CLINICA_CIRURGIA_GRANDES_ANIMAIS,
    DERMATOLOGIA,
    ENDOCRINOLOGIA,
    GINECOLOGIA_OBSTETRICIA,
    MEDICINA_FELINOS,
    MEDICINA_PEQUENOS_ANIMAIS,
    MEDICINA_TRABALHO,
    MEDICINA_PREVENTIVA_SAUDE_PUBLICA,
    NUTRICAO,
    ONCOLOGIA,
    OFTALMOLOGIA,
    PATOLOGIA,
    REPRODUCAO;

}

